[build]
  command = "bash -lc 'export GOPROXY=https://proxy.golang.org,direct && go install github.com/saintedlama/cecil/cmd/cecil@latest && export PATH=\"$(go env GOPATH)/bin:$PATH\" && cecil build'"
  publish = "_site"

[[redirects]]
  from = "/api/*"
  to = "http://159.65.10.189:8651/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/"
  to = "/admin/index.html"
  status = 200
