backend:
  name: git-gateway
  branch: main   # jis branch me tum content store karna chahte ho

media_folder: "images/uploads"   # images yahan save hongi
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
